steps:
  - template: templates/build-azure-devops-cli-extension.yml

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Azure DevOps CLI extension as artifact'
    inputs:
      pathtoPublish: 'azure-devops/dist' 
      artifactName: 'azure-devops-cli-extension' 
      publishLocation: 'Container'