steps:
- script: python -m pip install --upgrade pip
  displayName: 'Upgrade pip'
- script: pip install wheel
  displayName: 'Install Wheel'
- script: pip install pytest
  displayName: 'Install pytest'
- script: pip install coverage
  displayName: 'Install coverage'
- script: pip install pytest-cov
  displayName: 'Install pytest-cov'
- script: pip install --pre azure-cli --extra-index-url https://azurecliprod.blob.core.windows.net/edge
  displayName: 'Install Azure CLI'