name: Pull request Validation

pr:
- master
 
trigger: none
 
jobs:
  validate:
    runs-on: 'windows-latest'
 
  steps:
    -name: 'Install chef utils'
     run: gem install chef-utils -v 16.6.14
 
  - script: gem install mdl
    name: 'Install markdown lint'
 
  - script: mdl . -c .mdlrc
    name: 'Run markdown lint'